services:
  postgres:
    image: postgres:15-alpine
    container_name: steam_bi_postgres
    #restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-steam_bi}
      POSTGRES_USER: ${POSTGRES_USER:-steam_bi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-steam_bi_user}
      #TZ: ${TZ:-UTC}
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

#volumes:
#  postgres_data: