services:
  postgres:
    image: postgres:15-alpine
    container_name: steam_bi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: steam_bi
      POSTGRES_USER: steam_bi_user
      POSTGRES_PASSWORD: steam_bi_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steam_bi_user -d steam_bi"]
      interval: 10s
      timeout: 5s
      retries: 5
